services:
    jmusicbot:
        image: 'skyzi000/jmusicbot-jp:latest'
        container_name: 'jmusicbot'
        volumes:
            - ./logs:/jmusicbot/logs
            - ./Playlists:/jmusicbot/Playlists
            - ./Mylists:/jmusicbot/Mylists
            - ./Publist:/jmusicbot/Publist
            - type: bind
              source: ./config.txt
              target: /jmusicbot/config.txt
            - type: bind
              source: ./serversettings.json
              target: /jmusicbot/serversettings.json
        # restart: always
