name: Update JMusicBot Version

on:
  schedule:
    # 毎日午後8時(JST)にチェック
    - cron: '0 11 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest JMusicBot-JP version
        id: latest
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/Cosgy-Dev/JMusicBot-JP/releases | jq -r '.[0].tag_name')
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "Latest version: $LATEST_VERSION"

      - name: Get current version from Dockerfile
        id: current
        run: |
          CURRENT_VERSION=$(grep 'ENV JMUSICBOT_VERSION=' Dockerfile | cut -d'=' -f2)
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Check if update is needed
        id: check
        run: |
          if [ "${{ steps.latest.outputs.version }}" != "${{ steps.current.outputs.version }}" ]; then
            echo "Update needed: ${{ steps.current.outputs.version }} -> ${{ steps.latest.outputs.version }}"
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "No update needed"
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Dockerfile
        if: steps.check.outputs.update_needed == 'true'
        run: |
          sed -i "s/ENV JMUSICBOT_VERSION=.*/ENV JMUSICBOT_VERSION=${{ steps.latest.outputs.version }}/" Dockerfile
          cat Dockerfile

      - name: Download latest config.txt
        if: steps.check.outputs.update_needed == 'true'
        run: |
          # 最新のconfig.txtをダウンロードして完全に上書き
          CONFIG_URL=$(curl -s "https://api.github.com/repos/Cosgy-Dev/JMusicBot-JP/releases/tags/${{ steps.latest.outputs.version }}" | jq -r '.assets[] | select(.name == "config.txt") | .browser_download_url')
          if [ -n "$CONFIG_URL" ]; then
            echo "Downloading config.txt from: $CONFIG_URL"
            curl -SLo config.txt "$CONFIG_URL"
            echo "config.txt has been updated"
          else
            echo "Warning: config.txt not found in release assets"
          fi

      - name: Create Pull Request
        if: steps.check.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "JMusicBotのバージョンを${{ steps.latest.outputs.version }}に更新"
          title: "JMusicBotのバージョンを${{ steps.latest.outputs.version }}に更新"
          body: |
            JMusicBot-JPの新しいバージョン `${{ steps.latest.outputs.version }}` がリリースされました。
            
            ## 変更内容
            - Dockerfileのバージョンを更新
            - config.txtを最新版に更新
            
            ## リリース情報
            [リリースノート](https://github.com/Cosgy-Dev/JMusicBot-JP/releases/tag/${{ steps.latest.outputs.version }})
          branch: update-jmusicbot-${{ steps.latest.outputs.version }}
          base: develop
          delete-branch: true
